### ISSUE TITLE
Vggish is not available on PyTorch hub

### ISSUE THREAD

**Issue by zihaohe123** [gudgud96/frechet-audio-distance#20]
Hello, I was trying to use the Vggish model, but got the following error. It seems Vggish is not available on PyTorch Hub.

 UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/harritaylor/torchvggish/zipball/master" to /Users/zihaohe/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zihaohe/miniconda3/lib/python3.9/site-packages/torch/hub.py", line 555, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/Users/zihaohe/miniconda3/lib/python3.9/site-packages/torch/hub.py", line 230, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
  File "/Users/zihaohe/miniconda3/lib/python3.9/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/zihaohe/miniconda3/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

**Comment by gudgud96** [comment]
Unfortunately I am unable to reproduce your issue. Running `torch.hub.load(repo_or_dir='harritaylor/torchvggish', model='vggish', force_reload=True)` works fine for me, both locally and on our CI. VGGish should still be available on PyTorch Hub. This seems more like an isolated network issue.

**Comment by zihaohe123** [comment]
Hi, thank you so much for your reply! It seems the issue has been resolved and I'm also able to run it now.
So I guess PyTorch Hub server had some issues when I was trying to run it several days ago, as I tried to run exact same code on several different servers located in different places, and none of them worked.
